name: greek_quiz
description: Flutter port with real downloads and localization.
publish_to: "none"
version: 0.3.0+3

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_riverpod: ^2.5.1
  go_router: ^16.1.0
  shared_preferences: ^2.2.3
  http: ^1.2.2
  flutter_tts: ^4.2.3
  webview_flutter: ^4.8.0
  audio_service: ^0.18.13
  audio_session: ^0.2.2
  path_provider: ^2.1.4
  cupertino_icons: ^1.0.6
  flutter_lints: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  generate: true

# ИКОНКА
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png
  remove_alpha_ios: true

# СПЛЭШ (убираем логотип Flutter — чистый фон)
flutter_native_splash:
  android: true
  ios: true
  color: "#FFFFFF"
  android_12:
    color: "#FFFFFF"

dependency_overrides:
  characters: ^1.4.1
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
  vector_math: ^2.2.0
